### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by shirou93**
Add and translate new vaules:
```
      <string name="subscribe_unsubscribe_from_channel">Subskrybuj/Odsubskrybuj kanał</string>

	<string name="share_embed_link">Udostępnij link do osadzenia</string>

	<string name="add_remove_from_playback_queue">Dodaj/Usuń z kolejki odtwarzania</string>
```
Translate old values:
```
   <string name="option_background_playback_behind">Odtwarzaj w tle</string>

   <string name="update_changelog">Dziennik Zmian</string>

   <string name="option_background_playback_behind">Odtwarzaj w tle</string>

    <string name="update_in_progess">Trwa aktualizacja…</string>
```

### CODE REVIEW

**Review by RDKRACZ — APPROVED** [review]
Instead of "Trwa aktualizacja" maybe use "Aktualizacja w toku"

**Comment by shirou93** [comment]
> Instead of "Trwa aktualizacja" maybe use "Aktualizacja w toku"

Ok. Changed

**Comment by RDKRACZ** [comment]
@yuliskov a little question - do you know about this misspelling in lang files? `<string name="update_in_progess">`. I'm talking about the word "progress".

**Comment by yuliskov** [comment]
Didn't know that, thx.

Regards, Yuriy

**Pull request closed without merging**
