### PR TITLE
Dependency updates.

### PR DESCRIPTION
**Pull request by Mou-Ikkai**
Added a Dependabot config if you wish to activate Dependabot on the Master github. Along with this, 6 dependencies were updated.

Dependency updates:

- firebase-crashlytics-gradle: 2.7.1 -> 2.9.1
- flexbox: 1.0.0 -> 2.0.1
- google-services: 4.3.10 -> 4.3.13
- gradle: 3.5.4 -> 7.2.2 (Almost 5 years outdated!?)
- material: 1.2.1 -> 1.6.1
- webpdecoder: 2.0 -> 2.0.4.12.0

### CODE REVIEW

**Review by halotroop2288 — APPROVED** [review]

**Comment by yuliskov** [comment]
Thx, friend. I'll apply your patch manually.

**Comment by halotroop2288** [comment]
> Thx, friend. I'll apply your patch manually.

Or you could just squash-merge this, actually giving them credit for helping out, while keeping your commit history clean...

**Comment by Mou-Ikkai** [comment]
> > Thx, friend. I'll apply your patch manually.
> 
> Or you could just squash-merge this, actually giving them credit for helping out, while keeping your commit history clean...

Agreed... @yuliskov , can you Squash Merge this?

**Comment by yuliskov** [comment]
@Mou-Ikkai I'll update deps later. I'm not sure that this is really nesseary right now.

**Comment by Mou-Ikkai** [comment]
...Your Gradle is 5 years out of date. Besides that, a majority of these dependencies have had security fixes, crash fixes, and a lot of bug fixes. It's not that hard to just click the dropdown arrow and... Squash-Merge.

**Comment by Mou-Ikkai** [comment]
Like, I get it, you're the head of this project, but if you're going to ignore security and crash fixes then... That's not a good thing at all.

**Comment by yuliskov** [comment]
@Mou-Ikkai agree about gradle version. Maybe crashlytics too. Not sure about other ones. If only you provide a links where security britches are.

**Comment by Mou-Ikkai** [comment]
Flexbox 2.0.0 talks about significant performance improvements.
Material talks about constant alignment, bug, performance, and very small amounts of crash fixes.

**Comment by yuliskov** [comment]
@Mou-Ikkai got it. I'll check compatibility with Android 4.4 and do the upgrade.

**Pull request closed without merging**
