### PR TITLE
Support finish_on_ended intent extra

### LINKED ISSUE #1840: Support finish_on_ended intent extra
I'm the developer of [HopWatch](https://play.google.com/store/apps/details?id=com.ugglynoodle.hopwatch), a Reddit client for Android TV. HopWatch plays YouTube videos by launching an ACTION_VIEW intent. Currently only the official YouTube app is supported. However users have asked me to support alternative YouTube apps such as SmartTube so I'm planning to support this in the next release.

HopWatch sets the [`finish_on_ended` intent extra](https://developers.google.com/youtube/android/player/reference/com/google/android/youtube/player/YouTubeIntents#createPlayVideoIntentWithOptions(android.content.Context,%20java.lang.String,%20boolean,%20boolean)) which will make the YouTube app close when the video has ended, instead of auto-playing another video, so that the user returns to HopWatch. It would be great if SmartTube could also support this behaviour when handling a YouTube intent with the `finish_on_ended` intent extra. I have a pull request which implements this.

### PR DESCRIPTION
**Pull request by UgglyNoodle**
Resolves #1840

### CODE REVIEW

**Comment by UgglyNoodle** [comment]
Resolves #1840

**Comment by yuliskov** [comment]
Thx, friend. I'll review your request and apply.

**Comment by yuliskov** [comment]
Good work! I've merged your commit manually. Closing.

**Comment by UgglyNoodle** [comment]
Thank you!

**Pull request closed without merging**
